{{- range $name, $config := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.containerName }}
  labels:
    app: {{ $config.containerName }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $config.containerName }}
  template:
    metadata:
      labels:
        app: {{ $config.containerName }}
    spec:
      containers:
        - name: {{ $config.containerName }}
          image: {{ $config.image }}{{ if $config.tag }}:{{ $config.tag }}{{ end }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ or $config.targetPort $config.port }} # ← container thực sự chạy ở đây
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "{{ $config.containerName }}"
{{- end }}
