{{- range $name, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.containerName }}
spec:
  selector:
    app: {{ $config.containerName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ $config.port }}                             # ← Service expose cổng này
      targetPort: {{ or $config.targetPort $config.port }} # ← Pod thực sự lắng nghe ở đây
{{- end }}
